### PR TITLE
Fix GEM_PATH in rvm.fish for fish >= 2.2.0

### PR DESCRIPTION
**Pull request by drbig**
So this fixes broken `GEM_PATH` for me. Didn't investigate but given the only thing that changed between it working and not was the fish upgrade...

### CODE REVIEW

**Comment by lunks** [comment]
Could you please try on previous `fish` versions to make sure this is backwards-compatible? It looks like, I just want to be sure of it. :)

**Comment by drbig** [comment]
@lunks I'll try to test it now. That's a good point.

**Comment by drbig** [comment]
Ok not today (timezones are well...). I'll be happy if anyone beats me to testing it. One of my BSD boxes has older fish but not rvm... a place to test.

**Comment by drbig** [comment]
Confirmed. Also working as expected with `fish 2.0.0` (on FreeBSD 9.3 amd64).

**Comment by drbig** [comment]
Anything else blocking?

**Comment by drbig** [comment]
Ready for merge... Unless there's anything else I should do.

**Comment by talha131** [comment]
@drbig Thank you for submitting this patch. I spent a long time trying to figure out [why gems in @global gemset are not available](http://stackoverflow.com/q/32529350/177116). 

I request @lunks to please merge this patch. [Official documentation](https://rvm.io/integration/fish) has nothing on this bug. Newbies to Fish and rvm (like me) will waste a lot of time due to this bug.

**Comment by lunks** [comment]
Sorry for the long delay, folks! Merging it. :)

**Pull request merged**
